#!/usr/bin/env node

/**
 * DragonClaw CLI
 * 
 * Commands:
 *   dragonclaw onboard   — interactive setup wizard
 *   dragonclaw start      — start the gateway
 *   dragonclaw doctor     — diagnose config issues
 *   dragonclaw chat       — send a one-off message via CLI
 *   dragonclaw skills     — list loaded skills
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { createInterface } from 'readline';

const command = process.argv[2];

async function main() {
  switch (command) {
    case 'onboard':
      await onboard();
      break;
    case 'start':
      await import('./index.js');
      break;
    case 'doctor':
      await doctor();
      break;
    case 'chat':
      await chat();
      break;
    case 'skills':
      await listSkills();
      break;
    default:
      console.log(`
  🐉 DragonClaw 龙爪

  用法:
    dragonclaw onboard    交互式配置向导
    dragonclaw start      启动网关
    dragonclaw doctor     诊断配置问题
    dragonclaw chat       命令行聊天
    dragonclaw skills     列出已加载技能

  Usage:
    dragonclaw onboard    Interactive setup wizard
    dragonclaw start      Start the gateway
    dragonclaw doctor     Diagnose config issues
    dragonclaw chat       Chat via command line
    dragonclaw skills     List loaded skills
`);
  }
}

// ── Onboarding Wizard ──

async function onboard() {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q) => new Promise(resolve => rl.question(q, resolve));

  console.log(`
  🐉 DragonClaw 龙爪 — 配置向导
  ════════════════════════════════
  `);

  // 1. LLM Provider
  console.log('  可选模型 / Available LLM providers:');
  console.log('    1. DeepSeek      (推荐，便宜)');
  console.log('    2. 通义千问 Qwen  (阿里云)');
  console.log('    3. Kimi          (月之暗面)');
  console.log('    4. GLM           (智谱)');
  console.log('    5. OpenAI        (GPT-4o)');
  console.log('    6. Anthropic     (Claude)');
  console.log('    7. OpenRouter    (多模型代理)');
  console.log('');

  const providerMap = { '1': 'deepseek', '2': 'qwen', '3': 'kimi', '4': 'glm', '5': 'openai', '6': 'anthropic', '7': 'openrouter' };
  const provChoice = await ask('  选择模型 (1-7): ');
  const provider = providerMap[provChoice.trim()] || 'deepseek';

  const apiKey = await ask(`  ${provider} API Key: `);

  // 2. Binance (optional)
  console.log('\n  币安配置 (可选，按回车跳过):');
  const bnApiKey = await ask('  Binance API Key: ');
  const bnSecret = bnApiKey ? await ask('  Binance Secret Key: ') : '';
  const bnTestnet = bnApiKey ? (await ask('  使用测试网? (Y/n): ')).toLowerCase() !== 'n' : true;

  // 3. Connector
  console.log('\n  聊天平台 (可选，按回车跳过):');
  const tgToken = await ask('  Telegram Bot Token: ');
  const ddWebhook = await ask('  钉钉 Robot Webhook URL: ');

  // 4. Agent name
  const agentName = (await ask('\n  给你的龙爪起个名字 (默认: 龙爪): ')).trim() || '龙爪';

  // 5. Language
  const langChoice = await ask('  默认语言 / Default language (zh/en/auto): ');
  const language = ['zh', 'en', 'auto'].includes(langChoice.trim()) ? langChoice.trim() : 'zh';

  rl.close();

  // Generate config file
  const config = {
    llm: { provider, apiKey, model: null },
    binance: bnApiKey ? { apiKey: bnApiKey, secretKey: bnSecret, testnet: bnTestnet } : {},
    connectors: {
      telegram: tgToken ? { enabled: true, token: tgToken } : { enabled: false },
      dingtalk: ddWebhook ? { enabled: true, robotWebhook: ddWebhook } : { enabled: false },
    },
    agent: { name: agentName, language },
  };

  // Write config
  const configDir = join(homedir(), '.dragonclaw');
  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });

  const yamlContent = generateYaml(config);
  const configPath = join(configDir, 'dragonclaw.yaml');
  writeFileSync(configPath, yamlContent);

  console.log(`\n  ✓ 配置已保存到 ${configPath}`);
  console.log(`\n  下一步 / Next steps:`);
  console.log(`    dragonclaw start    启动龙爪`);
  console.log(`    dragonclaw chat     命令行聊天`);
  console.log(`    dragonclaw doctor   检查配置\n`);
}

function generateYaml(config) {
  let yaml = `# DragonClaw 龙爪 Configuration\n# Generated by: dragonclaw onboard\n\n`;

  yaml += `llm:\n`;
  yaml += `  provider: ${config.llm.provider}\n`;
  yaml += `  apiKey: "${config.llm.apiKey}"\n`;
  if (config.llm.model) yaml += `  model: ${config.llm.model}\n`;
  yaml += `\n`;

  if (config.binance.apiKey) {
    yaml += `binance:\n`;
    yaml += `  apiKey: "${config.binance.apiKey}"\n`;
    yaml += `  secretKey: "${config.binance.secretKey}"\n`;
    yaml += `  testnet: ${config.binance.testnet}\n\n`;
  }

  yaml += `connectors:\n`;
  if (config.connectors.telegram?.enabled) {
    yaml += `  telegram:\n    enabled: true\n    token: "${config.connectors.telegram.token}"\n`;
  }
  if (config.connectors.dingtalk?.enabled) {
    yaml += `  dingtalk:\n    enabled: true\n    robotWebhook: "${config.connectors.dingtalk.robotWebhook}"\n`;
  }
  yaml += `\n`;

  yaml += `agent:\n`;
  yaml += `  name: "${config.agent.name}"\n`;
  yaml += `  language: ${config.agent.language}\n`;
  yaml += `  confirmBeforeTrade: true\n`;
  yaml += `  heartbeatCron: "0 9 * * *"\n`;

  return yaml;
}

// ── Doctor ──

async function doctor() {
  console.log('\n  🐉 DragonClaw Doctor\n');
  const { loadConfig } = await import('./core/config.js');

  try {
    const config = await loadConfig();
    console.log(`  ✓ Config file found`);
    console.log(`  ${config.llm.provider ? '✓' : '✗'} LLM provider: ${config.llm.provider || 'NOT SET'}`);
    console.log(`  ${config.llm.apiKey ? '✓' : '✗'} LLM API key: ${config.llm.apiKey ? '***configured***' : 'NOT SET'}`);
    console.log(`  ${config.binance.apiKey ? '✓' : '○'} Binance API key: ${config.binance.apiKey ? '***configured***' : 'not set (optional)'}`);

    const connectors = Object.entries(config.connectors).filter(([, v]) => v.enabled);
    console.log(`  ${connectors.length > 0 ? '✓' : '○'} Connectors: ${connectors.length > 0 ? connectors.map(([k]) => k).join(', ') : 'none enabled'}`);

    // Check Node version
    const nodeVer = process.versions.node.split('.').map(Number);
    console.log(`  ${nodeVer[0] >= 20 ? '✓' : '✗'} Node.js: v${process.versions.node} (need >= 20)`);

    console.log(`\n  Binance skills (hardcoded): 7/7 ✓`);
    console.log(`  Skills directory: ${config.skills.userDir}\n`);
  } catch (e) {
    console.log(`  ✗ ${e.message}\n`);
  }
}

// ── Interactive Chat ──

async function chat() {
  const { loadConfig } = await import('./core/config.js');
  const { SkillManager } = await import('./core/skill-manager.js');
  const { AgentLoop } = await import('./core/agent-loop.js');
  const { MemoryStore } = await import('./core/memory.js');

  const config = await loadConfig();
  const memory = new MemoryStore(config.paths.data);
  await memory.init();
  const skills = new SkillManager(config);
  await skills.loadAll();
  const agent = new AgentLoop({ config, skills, memory });

  console.log(`\n  🐉 DragonClaw CLI Chat (输入 exit 退出)\n`);

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q) => new Promise(resolve => rl.question(q, resolve));

  while (true) {
    const input = await ask('  你: ');
    if (input.trim().toLowerCase() === 'exit') break;
    if (!input.trim()) continue;

    try {
      const reply = await agent.process('cli', 'cli-user', input.trim(), 'cli');
      console.log(`\n  🐉: ${reply}\n`);
    } catch (e) {
      console.log(`\n  ⚠ Error: ${e.message}\n`);
    }
  }

  rl.close();
  memory.close();
}

// ── List Skills ──

async function listSkills() {
  const { loadConfig } = await import('./core/config.js');
  const { SkillManager } = await import('./core/skill-manager.js');

  const config = await loadConfig();
  const skills = new SkillManager(config);
  await skills.loadAll();

  console.log(`\n  🐉 Loaded Skills\n`);
  for (const s of skills.all()) {
    const authTag = s.requiresAuth ? ' [需要密钥]' : ' [免密钥]';
    console.log(`  ${s.source === 'core' ? '⚡' : '📦'} ${s.title} (${s.slug})${authTag}`);
    if (s.description) console.log(`     ${s.description}`);
  }
  console.log(`\n  Core: ${skills.coreCount()} | User: ${skills.userCount()}\n`);
}

main().catch(console.error);
